# Generated by Django 4.0.6 on 2023-01-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='account.customer'),
        ),
    ]
