# Generated by Django 4.0.6 on 2023-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='course',
            field=models.CharField(choices=[('bcom', 'bcom'), ('bca', 'bca'), ('bba', 'bba')], max_length=20),
        ),
    ]
