# Generated by Django 4.0.6 on 2023-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_alter_address_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='course',
            field=models.CharField(choices=[('bca', 'bca'), ('bcom', 'bcom'), ('bba', 'bba')], max_length=20),
        ),
    ]
