# Generated by Django 4.1.7 on 2023-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_alter_address_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='course',
            field=models.CharField(choices=[('bba', 'bba'), ('bcom', 'bcom'), ('bca', 'bca')], max_length=20),
        ),
    ]
